import {
	searchApiKeys,
	searchApps,
	searchBuckets,
	searchDatabases,
	searchDedicatedDatabases,
	searchDocumentsDbCollections,
	searchDocumentsDbDatabases,
	searchFiles,
	searchFunctions,
	searchPlatforms,
	searchProviders,
	searchProxyRules,
	searchSites,
	searchTables,
	searchTeams,
	searchTopics,
	searchUsers,
	searchVectorsDbCollections,
	searchVectorsDbDatabases,
	searchWafRules,
	searchWebhooks,
} from './listSearch';
import {
	getAppInstallationScopes,
	getAvailablePostgresqlExtensions,
	getColumns,
	getFrameworks,
	getInstalledPostgresqlExtensions,
	getRuntimes,
	getSiteBuildRuntimes,
} from './loadOptions';
import {
	searchDnsRecords,
	searchDomains,
	searchOrganizationProjectKeys,
	searchOrganizationProjects,
} from './organizationListSearch';

/** The pickers behind the node's resource locators (From List mode). */
export const listSearch = {
	searchApiKeys,
	searchApps,
	searchBuckets,
	searchDatabases,
	searchDedicatedDatabases,
	searchDnsRecords,
	searchDocumentsDbCollections,
	searchDocumentsDbDatabases,
	searchDomains,
	searchFiles,
	searchFunctions,
	searchOrganizationProjectKeys,
	searchOrganizationProjects,
	searchPlatforms,
	searchProviders,
	searchProxyRules,
	searchSites,
	searchTables,
	searchTeams,
	searchTopics,
	searchUsers,
	searchVectorsDbCollections,
	searchVectorsDbDatabases,
	searchWafRules,
	searchWebhooks,
};

/** The dropdowns whose options load from Appwrite. */
export const loadOptions = {
	getAppInstallationScopes,
	getAvailablePostgresqlExtensions,
	getColumns,
	getFrameworks,
	getInstalledPostgresqlExtensions,
	getRuntimes,
	getSiteBuildRuntimes,
};
